server:
  servlet:
    session:
      timeout: 2592000
spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration
      - org.springframework.boot.autoconfigure.session.SessionAutoConfiguration
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: ${spring.servlet.multipart.max-file-size}
  profiles:
    active: dev
    include: secret
  mail:
    host: smtp.gmail.com
    port: 587
    username: jangka512@gmail.com
    password: NEED_TO_INPUT_ON_SECRET
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  datasource:
    url: jdbc:mariadb://localhost:3306/s_code_dev?useUnicode=true&characterEncoding=utf8mb4&collation=utf8mb4_unicode_ci
    username: root
    password: lldj123414
    driver-class-name: org.mariadb.jdbc.Driver
  security:
    oauth2:
      client:
        registration:
          kakao:
            clientId: NEED_TO_INPUT_ON_SECRET
            scope: profile_nickname, profile_image
            client-name: Kakao
            authorization-grant-type: authorization_code
            redirect-uri: '${custom.site.baseUrl}/{action}/oauth2/code/{registrationId}'
          kakaoForApi:
            clientId: NEED_TO_INPUT_ON_SECRET
            scope: profile_nickname, profile_image
            client-name: KakaoForApi
            authorization-grant-type: authorization_code
            redirect-uri: '${custom.site.baseUrl}/{action}/oauth2/code/{registrationId}'
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          kakaoForApi:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_batch_fetch_size: 100
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
    org.hibernate.orm.jdbc.extract: TRACE
    org.springframework.transaction.interceptor: TRACE
custom:
  tempDirPath: c:/temp/s_code/temp
  site:
    name: scode.gg
    baseUrl: "http://localhost:8090"
  genFile:
    dirPath: c:/temp/s_code
  security:
    oauth2:
      client:
        registration:
          kakao:
            devUserOauthId: 3058152288